import { AcademicType } from "@/components/editor/extensions/academic-block/academic-block";

export interface AcademicElementMeta {
    id: string;
    type: AcademicType;
    number: string;
    title: string;
    index: number;
    folded?: boolean;
}

export interface PostAcademicMeta {
    theorems: AcademicElementMeta[];
    definitions: AcademicElementMeta[];
    proofs: AcademicElementMeta[];
    others: AcademicElementMeta[];
    totalAcademicCount: number;
    crossRefCount: number;
    sidenoteCount: number;
}

/**
 * 递归遍历 Tiptap JSON 树，提取学术要素元数据
 */
export function extractAcademicMeta(content: unknown): PostAcademicMeta {
    const meta: PostAcademicMeta = {
        theorems: [],
        definitions: [],
        proofs: [],
        others: [],
        totalAcademicCount: 0,
        crossRefCount: 0,
        sidenoteCount: 0,
    };

    if (!content || typeof content !== "object") return meta;

    const typeCounters: Record<string, number> = {};

    function walk(node: any) {
        if (!node || typeof node !== "object") return;

        if (node.type === "academicBlock" && node.attrs) {
            const academicType = (node.attrs.academicType || "theorem") as AcademicType;
            typeCounters[academicType] = (typeCounters[academicType] || 0) + 1;
            const currentIndex = typeCounters[academicType];

            // 优先使用节点存储的 ID，若无则使用确定性学术序号锚点 ID
            const item: AcademicElementMeta = {
                id: node.attrs.academicId || `academic-${academicType}-${currentIndex}`,
                type: academicType,
                number: node.attrs.number || String(currentIndex),
                title: node.attrs.title || "",
                index: currentIndex,
                folded: Boolean(node.attrs.isFolded),
            };

            meta.totalAcademicCount++;

            if (academicType === "definition") {
                meta.definitions.push(item);
            } else if (academicType === "proof") {
                meta.proofs.push(item);
            } else if (academicType === "theorem" || academicType === "lemma" || academicType === "proposition" || academicType === "corollary") {
                meta.theorems.push(item);
            } else {
                meta.others.push(item);
            }
        }

        if (node.type === "crossRef") {
            meta.crossRefCount++;
        }

        if (node.type === "sidenote") {
            meta.sidenoteCount++;
        }

        if (Array.isArray(node.content)) {
            for (const child of node.content) {
                walk(child);
            }
        }
    }

    walk(content);
    return meta;
}

/**
 * 将 Tiptap ProseMirror 内容树转换为标准 LaTeX 源码格式
 */
export function academicToLatex(post: {
    title: string;
    author?: { username?: string };
    content: unknown;
    created_at?: string;
}): string {
    const lines: string[] = [];

    // LaTeX 文档导头
    lines.push("% Generated by Scholarly Academic Platform");
    lines.push("\\documentclass[11pt,a4paper]{article}");
    lines.push("\\usepackage[utf8]{inputenc}");
    lines.push("\\usepackage{amsmath,amssymb,amsfonts,amsthm}");
    lines.push("\\usepackage{graphicx}");
    lines.push("\\usepackage{hyperref}");
    lines.push("\\usepackage{listings}");
    lines.push("\\usepackage{xcolor}");
    lines.push("\\usepackage{geometry}");
    lines.push("\\geometry{margin=1in}");
    lines.push("");
    lines.push("% --- 定理环境配置 ---");
    lines.push("\\theoremstyle{plain}");
    lines.push("\\newtheorem{theorem}{定理}[section]");
    lines.push("\\newtheorem{lemma}[theorem]{引理}");
    lines.push("\\newtheorem{proposition}[theorem]{命题}");
    lines.push("\\newtheorem{corollary}[theorem]{推论}");
    lines.push("");
    lines.push("\\theoremstyle{definition}");
    lines.push("\\newtheorem{definition}{定义}[section]");
    lines.push("\\newtheorem{example}{例}[section]");
    lines.push("");
    lines.push("\\theoremstyle{remark}");
    lines.push("\\newtheorem{remark}{注}[section]");
    lines.push("");
    lines.push(`\\title{${escapeLatex(post.title || "学术论文讨论")}}`);
    lines.push(`\\author{${escapeLatex(post.author?.username || "Scholarly 匿名学者")}}`);
    lines.push(`\\date{${post.created_at ? new Date(post.created_at).toLocaleDateString("zh-CN") : "\\today"}}`);
    lines.push("");
    lines.push("\\begin{document}");
    lines.push("\\maketitle");
    lines.push("");

    function renderNode(node: any): string {
        if (!node) return "";

        // 纯文本节点
        if (node.type === "text") {
            let text = escapeLatex(node.text || "");
            if (node.marks && Array.isArray(node.marks)) {
                for (const mark of node.marks) {
                    if (mark.type === "bold") text = `\\textbf{${text}}`;
                    if (mark.type === "italic") text = `\\textit{${text}}`;
                    if (mark.type === "code") text = `\\texttt{${text}}`;
                }
            }
            return text;
        }

        // 交叉引用节点
        if (node.type === "crossRef" && node.attrs) {
            const target = node.attrs.targetId || "";
            const label = node.attrs.label || "引用";
            return `\\ref{${target}}`;
        }

        // 学术边注节点
        if (node.type === "sidenote" && node.attrs) {
            return `\\footnote{${escapeLatex(node.attrs.content || "")}}`;
        }

        const innerContent = (node.content || []).map(renderNode).join("");

        // 标题
        if (node.type === "heading" && node.attrs) {
            const level = node.attrs.level || 1;
            if (level === 1) return `\\section{${innerContent}}\n\n`;
            if (level === 2) return `\\subsection{${innerContent}}\n\n`;
            return `\\subsubsection{${innerContent}}\n\n`;
        }

        // 段落
        if (node.type === "paragraph") {
            return `${innerContent}\n\n`;
        }

        // 学术环境块
        if (node.type === "academicBlock" && node.attrs) {
            const type = node.attrs.academicType || "theorem";
            const title = node.attrs.title ? `[${escapeLatex(node.attrs.title)}]` : "";
            const id = node.attrs.academicId ? `\\label{${node.attrs.academicId}}\n` : "";

            if (type === "proof") {
                return `\\begin{proof}\n${id}${innerContent}\\end{proof}\n\n`;
            }
            return `\\begin{${type}}${title}\n${id}${innerContent}\\end{${type}}\n\n`;
        }

        // 代码块
        if (node.type === "codeBlock") {
            return `\\begin{lstlisting}\n${node.content?.[0]?.text || ""}\n\\end{lstlisting}\n\n`;
        }

        // 引用
        if (node.type === "blockquote") {
            return `\\begin{quote}\n${innerContent}\\end{quote}\n\n`;
        }

        // 列表
        if (node.type === "bulletList") {
            return `\\begin{itemize}\n${innerContent}\\end{itemize}\n\n`;
        }
        if (node.type === "orderedList") {
            return `\\begin{enumerate}\n${innerContent}\\end{enumerate}\n\n`;
        }
        if (node.type === "listItem") {
            return `  \\item ${innerContent.trim()}\n`;
        }

        return innerContent;
    }

    if (post.content && typeof post.content === "object" && Array.isArray((post.content as any).content)) {
        for (const block of (post.content as any).content) {
            lines.push(renderNode(block));
        }
    }

    lines.push("\\end{document}");
    return lines.join("\n");
}

/**
 * 将 Tiptap ProseMirror 内容树转换为标准 Markdown 格式
 */
export function academicToMarkdown(post: {
    title: string;
    author?: { username?: string };
    content: unknown;
    created_at?: string;
}): string {
    const lines: string[] = [];

    lines.push(`# ${post.title}`);
    lines.push(`> 作者: ${post.author?.username || "Scholarly 用户"} | 日期: ${post.created_at ? new Date(post.created_at).toLocaleDateString("zh-CN") : "今日"}\n`);

    function renderNode(node: any): string {
        if (!node) return "";

        if (node.type === "text") {
            let text = node.text || "";
            if (node.marks && Array.isArray(node.marks)) {
                for (const mark of node.marks) {
                    if (mark.type === "bold") text = `**${text}**`;
                    if (mark.type === "italic") text = `*${text}*`;
                    if (mark.type === "code") text = `\`${text}\``;
                }
            }
            return text;
        }

        if (node.type === "crossRef" && node.attrs) {
            return `[${node.attrs.label || "引用"}](#${node.attrs.targetId || ""})`;
        }

        if (node.type === "sidenote" && node.attrs) {
            return `[^${node.attrs.noteNumber || "1"}]`;
        }

        const innerContent = (node.content || []).map(renderNode).join("");

        if (node.type === "heading" && node.attrs) {
            const prefix = "#".repeat(node.attrs.level || 1);
            return `${prefix} ${innerContent}\n\n`;
        }

        if (node.type === "paragraph") {
            return `${innerContent}\n\n`;
        }

        if (node.type === "academicBlock" && node.attrs) {
            const typeUpper = (node.attrs.academicType || "theorem").toUpperCase();
            const title = node.attrs.title ? ` (${node.attrs.title})` : "";
            const num = node.attrs.number ? ` ${node.attrs.number}` : "";
            return `> [!${typeUpper}]${num}${title}\n> ${innerContent.trim().split("\n").join("\n> ")}\n\n`;
        }

        if (node.type === "codeBlock") {
            const lang = node.attrs?.language || "";
            return `\`\`\`${lang}\n${node.content?.[0]?.text || ""}\n\`\`\`\n\n`;
        }

        if (node.type === "blockquote") {
            return `> ${innerContent.trim()}\n\n`;
        }

        if (node.type === "listItem") {
            return `- ${innerContent.trim()}\n`;
        }

        return innerContent;
    }

    if (post.content && typeof post.content === "object" && Array.isArray((post.content as any).content)) {
        for (const block of (post.content as any).content) {
            lines.push(renderNode(block));
        }
    }

    return lines.join("\n");
}

function escapeLatex(text: string): string {
    return text
        .replace(/\\/g, "\\textbackslash ")
        .replace(/([&%$#_{}])/g, "\\$1")
        .replace(/~/g, "\\textasciitilde ")
        .replace(/\^/g, "\\textasciicircum ");
}
